name: cs61a_scheme
description: Dart implementation of 61A Scheme.
version: 2.0.0-beta
homepage: https://scheme.cs61a.org
author: Jen Thakar <jthakar@berkeley.edu>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^0.31.1
  dart2_constant: ^1.0.1
  markdown: ^1.1.1
  quiver_hashcode: ^1.0.0

dev_dependencies:
  # Implementation library
  cs61a_scheme_impl:
    path: ../dart_scheme_impl

  # Core library tools
  dart_style: 1.0.10
  dependency_validator: ^1.1.1
  grinder: ^0.8.0+3
  test: ^0.12.0

  # CLI REPL
  cli_repl: ^0.0.1

  # Web app building
  sass_builder: ^1.0.0
  build_runner: any
  build_web_compilers: any
